// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avhhusldyzhyycxxkyva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2aGh1c2xkeXpoeXljeHhreXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NDI4NjUsImV4cCI6MjA4NjQxODg2NX0.p-kPFL8RueCiKCXM9kgKb-eqHUI-f6gsSD_G13IIW0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});